/* jshint indent: 2 */
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('man_cometba', {
'tba_tba': {type: DataTypes.CHAR(12),allowNull: false,defaultValue: ' ',comment: "CLAVE DEL TRABAJADOR"  },
'nom_tba': {type: DataTypes.CHAR(60),allowNull: false,defaultValue: ' ',comment: "NOMBRE DEL TRABAJADOR"  },
'rfc_tba': {type: DataTypes.CHAR(13),allowNull: false,defaultValue: ' ',comment: "RFC"  },
'cur_tba': {type: DataTypes.CHAR(18),allowNull: false,defaultValue: ' ',comment: "CURP"  },
'fal_tba': {type: DataTypes.DATE,allowNull: false,comment: "FECHA DE ALTA"  },
'est_tba': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "ESTATUS B=BLOQUEADO A=ACTIVO"  },
'pga_pga': {type: DataTypes.CHAR(19),allowNull: false,defaultValue: ' ',comment: "PRESUPUESTO DE GASTO"  },
'ob1_tba': {type: DataTypes.STRING(128),allowNull: false,comment: "OBSERVACION 1"  },
'ob2_tba': {type: DataTypes.STRING(128),allowNull: false,comment: "OBSERVACION 2"  },
'ob3_tba': {type: DataTypes.STRING(128),allowNull: false,comment: "OBSERVACION 3"  },
'aug_tba': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "AUTORIZA GASTOS S=SI; N=NO"  },
'fir_tba': {type: DataTypes.TEXT,allowNull: false,comment: "FIRMA"  },
'hdi_tba': {type: DataTypes.TEXT,allowNull: false,comment: "HUELLA DIGITAL"  },
'fot_tba': {type: DataTypes.TEXT,allowNull: false,comment: "FOTO"  },
'suc_pge': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "SUCURSAL"  },
'unn_unn': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "Unidad de negocio a la que pertenece"  },
'pat_tba': {type: DataTypes.CHAR(25),allowNull: false,defaultValue: ' ',comment: "Apellido paterno"  },
'mat_tba': {type: DataTypes.CHAR(25),allowNull: false,defaultValue: ' ',comment: "Apellido materno"  },
'fna_tba': {type: DataTypes.DATE,allowNull: false,comment: "Fecha de nacimiento"  },
'sxo_tba': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "Sexo / [M] masculino / [F] femenino"  },
'edc_tba': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "Estado civil / [S]oltero / [C]asado / s[E]parado / [O]tro"  },
'nss_tba': {type: DataTypes.CHAR(11),allowNull: false,defaultValue: ' ',comment: "Numero seguro social"  },
'nri_tba': {type: DataTypes.CHAR(11),allowNull: false,defaultValue: ' ',comment: "Numero de infonavit"  },
'lic_tba': {type: DataTypes.CHAR(10),allowNull: false,defaultValue: ' ',comment: "Numero de licencia de conducir"  },
'lvi_tba': {type: DataTypes.DATE,allowNull: false,comment: "Fecha de vigencia de licencia"  },
'dca_tba': {type: DataTypes.CHAR(40),allowNull: false,defaultValue: ' ',comment: "Direccion calle"  },
'dne_tba': {type: DataTypes.CHAR(10),allowNull: false,defaultValue: ' ',comment: "Direccion numero exterior"  },
'dni_tba': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "Direccion numero interior"  },
'dsc_tba': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "Direccion sector / colonia"  },
'dcp_tba': {type: DataTypes.CHAR(5),allowNull: false,defaultValue: ' ',comment: "Direccion CP."  },
'dcd_tba': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "Direccion ciudad"  },
'ded_tba': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "Direccion estado"  },
'env_tba': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "Estudios / [S]ecundaria / [P]reparatoria / [T]ecnico /[L]icenciatura / [O]tro"  },
'eds_tba': {type: DataTypes.CHAR(15),allowNull: false,defaultValue: ' ',comment: "Estudios carrera / licenciatura"  },
'ein_tba': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "Estudios institucion"  },
'eed_tba': {type: DataTypes.DECIMAL(1,0),allowNull: false,defaultValue: '0',comment: "Estudios estado certificado / titulo"  },
'ean_tba': {type: DataTypes.CHAR(4),allowNull: false,defaultValue: ' ',comment: "Estudios año de terminacion"  },
'sfe_tba': {type: DataTypes.DATE,allowNull: false,comment: "Separacion fecha"  },
'stp_tba': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "Por / [R]enuncia / [T]ermino / [D]espido / [P]ension / [O]tro"  },
'smo_tba': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "Separacion motivo"  },
'stt_tba': {type: DataTypes.DECIMAL(1,0),allowNull: false,defaultValue: '0',comment: "Status / [1] activo / [2] incapacitado / [3] inactivo / [4] baja / [5] prospecto"  },
'icr_tba': {type: DataTypes.DECIMAL(1,0),allowNull: false,defaultValue: '0',comment: "Imagen del CURP / [0] NO / [1] SI"  },
'irf_tba': {type: DataTypes.DECIMAL(1,0),allowNull: false,defaultValue: '0',comment: "Imagen del RFC / [0] NO [1] SI"  },
'ilc_tba': {type: DataTypes.DECIMAL(1,0),allowNull: false,defaultValue: '0',comment: "Imagen de LICENCIA / [0] NO / [1] SI"  },
'ife_tba': {type: DataTypes.DECIMAL(1,0),allowNull: false,defaultValue: '0',comment: "Imagen del IFE / [0] NO / [1] SI"  },
'icp_tba': {type: DataTypes.DECIMAL(1,0),allowNull: false,defaultValue: '0',comment: "Imagen de CEDULA PROF. / [0] NO / [1] SI"  },
'tip_tba': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "Tipo de empleado [S]indicalizado / [C]onfianza / [T]emporal"  },
'tip_hpe': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "Periocidad de pago / [S]emanal / [D]ecenal / [Q]uincenal / [M]es"  },
'cod_nom': {type: DataTypes.CHAR(12),allowNull: false,defaultValue: ' ',comment: "Codigo como vendedor en SIAVCOM"  },
'uca_tba': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "Talla de camisa uniforme"  },
'upa_tba': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "Talla pantalon en pulgadas"  },
'uza_tba': {type: DataTypes.CHAR(4),allowNull: false,defaultValue: ' ',comment: "Talla de zapato"  },
'tur_tba': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "Turno [M]atutino / [V]espertino / [N]octurno  /  [X]mixto"  },
'reg_bor': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "Indicador de estado de registro"  },
'usu_usu': {type: DataTypes.SMALLINT,allowNull: true,defaultValue: '0',comment: "USUARIO"  },
'usu_cre': {type: DataTypes.SMALLINT,allowNull: true,defaultValue: '0',comment: "USUARIO CREADOR" },
'tie_uac': {type: DataTypes.DATE,allowNull: true,comment: "FECHA DE LA ULTIMA ACTUALIZACION"  },
'tie_cre': {type: DataTypes.DATE,allowNull: true,comment: "FECHA DE CREACION" },
'timestamp': {type: DataTypes.INTEGER,allowNull: true,comment: "MARCA DE ULTIMA ACTUALIZACION"  },
'key_pri': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "LLAVE PRIMARIA PARA LA ACTUALIZACION DE VISTAS" , primaryKey: true },
createdAt: {field: 'tie_cre',type: DataTypes.DATE,},
updatedAt: {field: 'tie_uac',type: DataTypes.DATE,} 
  }, { tableName: 'man_cometba'});
};

