/* jshint indent: 2 */
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('man_comecam', {
'cam_cam': {type: DataTypes.SMALLINT,allowNull: false,defaultValue: '0',comment: "CAMION"  },
'mar_cam': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "MARCA SEGUN TABLA COMEMAR"  },
'tiu_tiu': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "TIPO SEGUN TABLA COMETIU"  },
'mod_mod': {type: DataTypes.CHAR(32),allowNull: false,defaultValue: ' ',comment: "MODELO"  },
'ano_cam': {type: DataTypes.SMALLINT,allowNull: false,defaultValue: '0',comment: "A¥O DEL VEHICULO"  },
'fad_cam': {type: DataTypes.DATE,allowNull: false,comment: "FECHA DE ADQUISICION"  },
'mar_mar': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "MARCA"  },
'cap_cam': {type: DataTypes.DECIMAL(12,2),allowNull: false,defaultValue: '0',comment: "CAPACIDAD DE CARGA"  },
'uni_cam': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "UNIDAD DE LA CAPACIDAD DE CARGA"  },
'uco_cam': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "UNIDAD DE CONTROL   K=kilometros; M=Millas; H=Horas; S=Sin control"  },
'ser_cam': {type: DataTypes.CHAR(30),allowNull: false,defaultValue: ' ',comment: "SERIE"  },
'dis_cam': {type: DataTypes.CHAR(50),allowNull: false,defaultValue: ' ',comment: "DISTRIBUIDORA A QUIEN SE COMPRO"  },
'fac_cam': {type: DataTypes.CHAR(12),allowNull: false,defaultValue: ' ',comment: "NUMERO DE FACTURA"  },
'pla_cam': {type: DataTypes.CHAR(10),allowNull: false,defaultValue: ' ',comment: "PLACAS"  },
'pol_cam': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "POLIZA DE SEGURO"  },
'cse_cam': {type: DataTypes.CHAR(50),allowNull: false,defaultValue: ' ',comment: "COMPAÑIA DE SEGUROS"  },
'tsi_cam': {type: DataTypes.CHAR(30),allowNull: false,defaultValue: ' ',comment: "TELEFONOS DE SINIESTROS"  },
'fiv_cam': {type: DataTypes.DATE,allowNull: false,comment: "FECHA INICIAL DE VIGENCIA"  },
'ffv_cam': {type: DataTypes.DATE,allowNull: false,comment: "FECHA FINAL DE VIGENCIA"  },
'obs_cam': {type: DataTypes.CHAR(60),allowNull: false,defaultValue: ' ',comment: "OBSERVACIONES"  },
'edo_cam': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "ESTADO A=ACTIVO; D=DESACTIVO; R=REPARACION; B=BAJA;O=OTRO"  },
'unn_unn': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "UNIDAD DE NEGOCIOS"  },
'com_cam': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "TIPO DE COMBUSTIBLE UTILIZADO"  },
'ren_cam': {type: DataTypes.DECIMAL(8,4),allowNull: false,defaultValue: '0',comment: "RENDIMIENTO"  },
'gar_cam': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "GARANTIA"  },
'tpg_cam': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "TIPO DE PERIDO DE GRANTIA ALTERNO"  },
'tga_cam': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "TIPO DE GARANTIA"  },
'pga_cam': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "PERIODO DE GARANTIA"  },
'ob1_cam': {type: DataTypes.STRING(256),allowNull: false,comment: "OBSERVACION 1"  },
'usu_usu': {type: DataTypes.SMALLINT,allowNull: true,defaultValue: '0',comment: "USUARIO"  },
'usu_cre': {type: DataTypes.SMALLINT,allowNull: true,defaultValue: '0',comment: "USUARIO CREADOR" },
'tie_uac': {type: DataTypes.DATE,allowNull: true,comment: "FECHA DE LA ULTIMA ACTUALIZACION"  },
'tie_cre': {type: DataTypes.DATE,allowNull: true,comment: "FECHA DE CREACION" },
'timestamp': {type: DataTypes.INTEGER,allowNull: true,comment: "MARCA ULTIMA ACTUALIZACION"  },
'key_pri': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "LLAVE PRIMARIA PARA LA ACTUALIZACION DE VISTAS" , primaryKey: true },
createdAt: {field: 'tie_cre',type: DataTypes.DATE,},
updatedAt: {field: 'tie_uac',type: DataTypes.DATE,} 
  }, { tableName: 'man_comecam'});
};

