/* jshint indent: 2 */
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('man_comepro', {
'cla_isu': {type: DataTypes.CHAR(30),allowNull: false,defaultValue: ' ',comment: "CLAVE DEL INSUMO"  },
'sse_pro': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "S=SERIE L=LOTE M=MEDIDAS N=NIGUNO"  },
'dga_pro': {type: DataTypes.SMALLINT,allowNull: false,defaultValue: '0',comment: "DIAS DE GARANTIA"  },
'pim_pro': {type: DataTypes.SMALLINT,allowNull: false,defaultValue: '0',comment: "1=SI; 0=NO PRODUCTO IMPORTADO"  },
'arc_tar': {type: DataTypes.CHAR(8),allowNull: false,defaultValue: ' ',comment: "ARANCEL DE IMPORTACION"  },
'pai_tar': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "PAIS DE ORIGEN"  },
'pes_pro': {type: DataTypes.DECIMAL(12,4),allowNull: false,defaultValue: '0',comment: "PESO KGM"  },
'vol_pro': {type: DataTypes.DECIMAL(12,4),allowNull: false,defaultValue: '0',comment: "VOLUMEN EN LITROS"  },
'mon_pro': {type: DataTypes.SMALLINT,allowNull: false,defaultValue: '0',comment: "MONEDA"  },
'cin_pro': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "CLASIFICACION DE INVENTARIO"  },
'fe1_pro': {type: DataTypes.DATE,allowNull: false,comment: "FECHA 1 ULTIMA ENTRADA"  },
'fe2_pro': {type: DataTypes.DATE,allowNull: false,comment: "FECHA 2 ULTIMA ENTRADA"  },
'fe3_pro': {type: DataTypes.DATE,allowNull: false,comment: "FECHA 3 ULTIMA ENTRADA"  },
'pr1_pro': {type: DataTypes.CHAR(12),allowNull: false,defaultValue: ' ',comment: "PROVEEDOR 1"  },
'pr2_pro': {type: DataTypes.CHAR(12),allowNull: false,defaultValue: ' ',comment: "PROVEEDOR 2"  },
'pr3_pro': {type: DataTypes.CHAR(12),allowNull: false,defaultValue: ' ',comment: "PROVEEDOR 3"  },
'pu1_pro': {type: DataTypes.DECIMAL(15,4),allowNull: false,defaultValue: '0',comment: "PRECIO 1 ULTIMA ENTRADA"  },
'pu2_pro': {type: DataTypes.DECIMAL(15,4),allowNull: false,defaultValue: '0',comment: "PRECIO 2 ULTIMA ENTRADA"  },
'pu3_pro': {type: DataTypes.DECIMAL(15,4),allowNull: false,defaultValue: '0',comment: "PRECIO 3 ULTIMA ENTRADA"  },
'mo1_pro': {type: DataTypes.SMALLINT,allowNull: false,defaultValue: '0',comment: "MONEDA 1 DE ULTIMA ENTRADA"  },
'mo2_pro': {type: DataTypes.SMALLINT,allowNull: false,defaultValue: '0',comment: "MONEDA 2 DE ULTIMA ENTRADA"  },
'mo3_pro': {type: DataTypes.SMALLINT,allowNull: false,defaultValue: '0',comment: "MONEDA 3 ULTIMA ENTRADA"  },
'fes_pro': {type: DataTypes.DATE,allowNull: false,comment: "FECHA ULTIMA SALIDA"  },
'cli_pro': {type: DataTypes.CHAR(12),allowNull: false,defaultValue: ' ',comment: "CLIENTE ULTIMA SALIDA"  },
'pus_pro': {type: DataTypes.DECIMAL(11,2),allowNull: false,defaultValue: '0',comment: "PRECIO UNITARIO ULTIMA SALIDA"  },
'tlc_pro': {type: DataTypes.DECIMAL(7,0),allowNull: false,defaultValue: '0',comment: "TAMAÑO DE LOTE DE COMPRA (MUL O MIN"  },
'tep_pro': {type: DataTypes.SMALLINT,allowNull: false,defaultValue: '0',comment: "TIEMPO DE ENTREGA EN DIAS"  },
'cmp_pro': {type: DataTypes.DECIMAL(12,4),allowNull: false,defaultValue: '0',comment: "CONSUMO MENSUAL PROMEDIO"  },
'fae_pro': {type: DataTypes.DECIMAL(5,2),allowNull: false,defaultValue: '0',comment: "FACTOR DE ESTACIONALIDAD"  },
'tca_pro': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "TIPO DE CALCULO M=MANUAL A=AUTOMATICO"  },
'fim_pro': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "FACTOR DE IMPORTANCIA"  },
'gdc_pro': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "GRADO DE DIFICULTAD DE CONTEO"  },
'fuc_pro': {type: DataTypes.DATE,allowNull: false,comment: "FECHA ULTIMO CONTEO"  },
'sca_pro': {type: DataTypes.SMALLINT,allowNull: false,defaultValue: '0',comment: "1= NO SE A CALCULADO COSTOS"  },
'pco_pro': {type: DataTypes.DECIMAL(15,4),allowNull: false,defaultValue: '0',comment: "PRECIO DE COSTEO"  },
'prr_pro': {type: DataTypes.DECIMAL(15,4),allowNull: false,defaultValue: '0',comment: "PRECIO DE REPOSICION"  },
'fpr_pro': {type: DataTypes.DATE,allowNull: false,comment: "FECHA DE CALCULO DE PRECIO DE REPOSICION"  },
'exe_pro': {type: DataTypes.DECIMAL(14,6),allowNull: false,defaultValue: '0',comment: "EXISTENCIA DEL EJERCICIO ANTES DE ACT."  },
'coe_pro': {type: DataTypes.DECIMAL(18,6),allowNull: false,defaultValue: '0',comment: "COSTO DE LA EXISTENCIA EJER. ANT. ACT"  },
'exp_pro': {type: DataTypes.DECIMAL(14,6),allowNull: false,defaultValue: '0',comment: "EXISTENCIA DEL PERIODO"  },
'cop_pro': {type: DataTypes.DECIMAL(18,6),allowNull: false,defaultValue: '0',comment: "COSTO POR PERIODO"  },
'med_pro': {type: DataTypes.STRING(256),allowNull: false,comment: "MEDIDAS DEL PRODUCTO"  },
'vem_pro': {type: DataTypes.DECIMAL(12,4),allowNull: false,defaultValue: '0',comment: "VOLUMEN  DEL EMPAQUE"  },
'viu_pro': {type: DataTypes.SMALLINT,allowNull: false,defaultValue: '0',comment: "VIDA UTIL"  },
'pvu_pro': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "PERIODO DE VIDA UTIL D=DIAS; S=SEMANAS; M=MESES; A=AÑO; U=USOS; N=NO tiene"  },
'tip_pro': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "TIPO DE PRODUCTO P=PRODUCCION; V=VENTA; H=HERRAMIENTA; S=SEGURIDAD"  },
'usu_usu': {type: DataTypes.SMALLINT,allowNull: true,defaultValue: '0',comment: "USUARIO"  },
'usu_cre': {type: DataTypes.SMALLINT,allowNull: true,defaultValue: '0',comment: "USUARIO CREADOR" },
'tie_uac': {type: DataTypes.DATE,allowNull: true,comment: "FECHA DE LA ULTIMA ACTUALIZACION"  },
'tie_cre': {type: DataTypes.DATE,allowNull: true,comment: "FECHA DE CREACION" },
'timestamp': {type: DataTypes.INTEGER,allowNull: true,comment: "MARCA ULTIMA ACTUALIZACION"  },
'key_pri': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "LLAVE PRIMARIA PARA LA ACTUALIZACION DE VISTAS" , primaryKey: true },
createdAt: {field: 'tie_cre',type: DataTypes.DATE,},
updatedAt: {field: 'tie_uac',type: DataTypes.DATE,} 
  }, { tableName: 'man_comepro'});
};

