//const { Sequelize } = require(".");
const { Sequelize,DataTypes } = require('sequelize');

/* jshint indent: 2 */
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('man_comeisu', {
'TIN_TTI': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "null" },
'CLA_ISU': {type: DataTypes.CHAR(30),allowNull: false,defaultValue: ' ',comment: "null" },
'DES_ISU': {type: DataTypes.CHAR(70),allowNull: false,defaultValue: ' ',comment: "null" },
'DPA_ISU': {type: DataTypes.BOOLEAN,allowNull: false,comment: "null" },
'DEA_ISU': {type: DataTypes.TEXT,allowNull: true,comment: "null" },
'UN1_ISU': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "null" },
'UN2_ISU': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "null" },
'UN3_ISU': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "null" },
'FA2_ISU': {type: DataTypes.DECIMAL(9,4),allowNull: false,defaultValue: '0',comment: "null" },
'FA3_ISU': {type: DataTypes.DECIMAL(9,4),allowNull: false,defaultValue: '0',comment: "null" },
'PV1_ISU': {type: DataTypes.DECIMAL(15,5),allowNull: false,defaultValue: '0',comment: "null" },
'PV2_ISU': {type: DataTypes.DECIMAL(15,5),allowNull: false,defaultValue: '0',comment: "null" },
'PV3_ISU': {type: DataTypes.DECIMAL(15,5),allowNull: false,defaultValue: '0',comment: "null" },
'PV4_ISU': {type: DataTypes.DECIMAL(15,5),allowNull: false,defaultValue: '0',comment: "null" },
'PV5_ISU': {type: DataTypes.DECIMAL(15,5),allowNull: false,defaultValue: '0',comment: "null" },
'TA0_ISU': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "null" },
'IM0_ISU': {type: DataTypes.BOOLEAN,allowNull: false,comment: "null" },
'TA1_ISU': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "null" },
'IM1_ISU': {type: DataTypes.BOOLEAN,allowNull: false,comment: "null" },
'TA2_ISU': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "null" },
'IM2_ISU': {type: DataTypes.BOOLEAN,allowNull: false,comment: "null" },
'TA3_ISU': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "null" },
'IM3_ISU': {type: DataTypes.BOOLEAN,allowNull: false,comment: "null" },
'TA4_ISU': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "null" },
'IM4_ISU': {type: DataTypes.BOOLEAN,allowNull: false,comment: "null" },
'TA5_ISU': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "null" },
'IM5_ISU': {type: DataTypes.BOOLEAN,allowNull: false,comment: "null" },
'UNI_SAT': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "null" },
'UBF_SAT': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "null" },
'CLS_SAT': {type: DataTypes.CHAR(8),allowNull: false,defaultValue: ' ',comment: "null" },
'FUM_SAT': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "null" },
'MON_ISU': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "null" },
'CST_ISU': {type: DataTypes.DECIMAL(12,4),allowNull: false,defaultValue: '0',comment: "null" },
'SKU_ISU': {type: DataTypes.CHAR(19),allowNull: false,defaultValue: ' ',comment: "null" },
'EST_ISU': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "null" },
'PVP_ISU': {type: DataTypes.DECIMAL(15,5),allowNull: false,defaultValue: '0',comment: "null" },
'DST_ISU': {type: DataTypes.CHAR(60),allowNull: false,defaultValue: ' ',comment: "null" },
'TCI_ISU': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "null" },
'DU1_ISU': {type: DataTypes.CHAR(14),allowNull: false,defaultValue: ' ',comment: "null" },
'DU2_ISU': {type: DataTypes.CHAR(14),allowNull: false,defaultValue: ' ',comment: "null" },
'DU3_ISU': {type: DataTypes.CHAR(14),allowNull: false,defaultValue: ' ',comment: "null" },
'FRA_ISU': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "null" },
'USU_USU': {type: DataTypes.INTEGER,allowNull: true,defaultValue: '0',comment: "null" },
'USU_CRE': {type: DataTypes.INTEGER,allowNull: true,defaultValue: '0',comment: "null" },
'TIE_UAC': {type: DataTypes.DATE,allowNull: true,comment: "null" },
'CRE_UAC': {type: DataTypes.DATE,allowNull: true,comment: "null" },
'Timestamp': {type: DataTypes.INTEGER,allowNull: true,comment: "null" },
'Key_pri': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "null" },
createdAt: {field: 'tie_uac',type: DataTypes.DATE,},
updatedAt: {field: 'tie_uac',type: DataTypes.DATE,} 
  }, { tableName: 'man_comeisu'});
};
