/* jshint indent: 2 */
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('man_comemov', {
'suc_pge': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "SUCURSAL"  },
'tdo_tdo': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "TIPO DE DOCUMENTO"  },
'ndo_doc': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "NUMERO DE DOCUMENTO"  },
'mov_mov': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "NUMERO DE MOVIMIENTO"  },
'ens_mov': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "DETALLE DE ENSAMBLE"  },
'inv_tdo': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "E=ENTRADA S=SALIDA N=NO AFECTA"  },
'cla_isu': {type: DataTypes.CHAR(30),allowNull: false,defaultValue: ' ',comment: "CLAVE DEL INSUMO"  },
'dse_mov': {type: DataTypes.STRING(2048),allowNull: false,comment: "DESCRIPCION DE PASO"  },
'ser_mov': {type: DataTypes.CHAR(17),allowNull: false,defaultValue: ' ',comment: "SERIE O LOTE"  },
'dga_pro': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "DIAS DE GARANTIA"  },
'ped_ped': {type: DataTypes.CHAR(15),allowNull: false,defaultValue: ' ',comment: "PEDIMENTO DE IMPORTACION"  },
'can_mov': {type: DataTypes.DECIMAL(12,5),allowNull: false,defaultValue: '0',comment: "CANTIDAD"  },
'med_mov': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "MEDIDA"  },
'pve_mov': {type: DataTypes.DECIMAL(16,6),allowNull: false,defaultValue: '0',comment: "PRECIO"  },
'de1_mov': {type: DataTypes.DECIMAL(5,2),allowNull: false,defaultValue: '0',comment: "DESCUENTO 1"  },
'de2_mov': {type: DataTypes.DECIMAL(5,2),allowNull: false,defaultValue: '0',comment: "DESCUENTO 2"  },
'de3_mov': {type: DataTypes.DECIMAL(5,2),allowNull: false,defaultValue: '0',comment: "DESCUENTO 3"  },
'de4_mov': {type: DataTypes.DECIMAL(5,2),allowNull: false,defaultValue: '0',comment: "DESCUENTO 4"  },
'de5_mov': {type: DataTypes.DECIMAL(5,2),allowNull: false,defaultValue: '0',comment: "DESCUENTO 5"  },
'im0_mov': {type: DataTypes.DECIMAL(10,5),allowNull: false,defaultValue: '0',comment: "IMPUESTO 0 % O CANTIDAD"  },
'im1_mov': {type: DataTypes.DECIMAL(10,5),allowNull: false,defaultValue: '0',comment: "IMPUESTO 1 % O CANTIDAD"  },
'im2_mov': {type: DataTypes.DECIMAL(10,5),allowNull: false,defaultValue: '0',comment: "IMPUESTO 2 % O CANTIDAD"  },
'im3_mov': {type: DataTypes.DECIMAL(10,5),allowNull: false,defaultValue: '0',comment: "IMPUESTO 3 % O CANTIDAD"  },
'im4_mov': {type: DataTypes.DECIMAL(10,5),allowNull: false,defaultValue: '0',comment: "IMPUESTO 4 % O CANTIDAD"  },
'im5_mov': {type: DataTypes.DECIMAL(10,5),allowNull: false,defaultValue: '0',comment: "IMPUESTO 5 % O CANTIDAD"  },
'tba_tba': {type: DataTypes.CHAR(12),allowNull: false,defaultValue: ' ',comment: "TRABAJADOR"  },
'pga_pga': {type: DataTypes.CHAR(19),allowNull: false,defaultValue: ' ',comment: "PRESUPUESTO DE GASTO"  },
'mon_mov': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "MONEDA"  },
'adv_tar': {type: DataTypes.DECIMAL(9,4),allowNull: false,defaultValue: '0',comment: "ADVALOREM"  },
'cuo_tar': {type: DataTypes.DECIMAL(10,2),allowNull: false,defaultValue: '0',comment: "CUOTA COMPENSATORIA"  },
'cpu_tar': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "CUOTA COMPEN. POR P=PORCENTAJE; U=UNIDAD"  },
'fec_mov': {type: DataTypes.DATE,allowNull: false,comment: "FECHA DEL MOVIMIENTO O DE ENTREGA"  },
'fme_mov': {type: DataTypes.DATE,allowNull: false,comment: "FECHA MAXIMA DE ENTREGA (PEDIDOS)"  },
'dpe_mov': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "DOCUMENTO DEL PEDIDO"  },
'npe_mov': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "NUMERO DE PEDIDO SURTIDO"  },
'mpe_mov': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "MOVIMIENTO DE PEDIDO SURTIDO"  },
'alm_tda': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "ALMACEN"  },
'spi_mov': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "SW DE PEDIMENTOS DE IMP. D=DESACTIVO"  },
'sns_mov': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "SW DE NUMEROS DE SERIE D=DESACTIVO"  },
'cen_mov': {type: DataTypes.DECIMAL(12,5),allowNull: false,defaultValue: '0',comment: "CANTIDAD ENTREGADA"  },
'tpe_mov': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "TIPO DE PRECIO DADO N='NORMAL C=CONTRATO; T=TIPO DE CLIENTE"  },
'est_mov': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "ESTATUS M=MANTENIMIENTO A=ACTIVO B=BLOQUEADO"  },
'obs_mov': {type: DataTypes.STRING(254),allowNull: false,comment: "OBSERVACIONES"  },
'usu_usu': {type: DataTypes.INTEGER,allowNull: true,defaultValue: '0',comment: "USUARIO"  },
'usu_cre': {type: DataTypes.INTEGER,allowNull: true,defaultValue: '0',comment: "USUARIO CREADOR" },
'tie_uac': {type: DataTypes.DATE,allowNull: true,comment: "FECHA DE LA ULTIMA ACTUALIZACION"  },
'tie_cre': {type: DataTypes.DATE,allowNull: true,comment: "FECHA DE CREACION" },
'timestamp': {type: DataTypes.INTEGER,allowNull: true,comment: "MARCA ULTIMA ACTUALIZACION"  },
'key_pri': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "LLAVE PRIMARIA PARA LA ACTUALIZACION DE VISTAS" , primaryKey: true },
createdAt: {field: 'tie_cre',type: DataTypes.DATE,},
updatedAt: {field: 'tie_uac',type: DataTypes.DATE,} 
  }, { tableName: 'man_comemov'});
};

