/* jshint indent: 2 */
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('man_comenom', {
'suc_pge': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "SUCURSAL"  },
'cop_nom': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "TIPO C=CLIENTES P=PROVEEDORES"  },
'cod_nom': {type: DataTypes.CHAR(12),allowNull: false,defaultValue: ' ',comment: "CODIGO DEL CLIENTE O PROVEEDOR"  },
'cli_nom': {type: DataTypes.CHAR(40),allowNull: false,defaultValue: ' ',comment: "NOMBRE CORTO O COMERCIAL"  },
'nom_nom': {type: DataTypes.CHAR(135),allowNull: false,defaultValue: ' ',comment: "NOMBRE FISCAL"  },
'nre_nom': {type: DataTypes.CHAR(35),allowNull: false,defaultValue: ' ',comment: "NOMBRE DEL REPRESENTANTE"  },
'rfc_nom': {type: DataTypes.CHAR(13),allowNull: false,defaultValue: ' ',comment: "R.F.C."  },
'dir_nom': {type: DataTypes.CHAR(120),allowNull: false,defaultValue: ' ',comment: "DIRECCION"  },
'ext_nom': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "NUMERO EXTERIOR"  },
'int_nom': {type: DataTypes.CHAR(60),allowNull: false,defaultValue: ' ',comment: "INTERIOR"  },
'col_nom': {type: DataTypes.CHAR(80),allowNull: false,defaultValue: ' ',comment: "COLONIA"  },
'pob_nom': {type: DataTypes.CHAR(120),allowNull: false,defaultValue: ' ',comment: "POBLACION"  },
'cpo_nom': {type: DataTypes.CHAR(5),allowNull: false,defaultValue: ' ',comment: "C.POSTAL"  },
'edo_edo': {type: DataTypes.CHAR(25),allowNull: false,defaultValue: ' ',comment: "ESTADO"  },
'pai_nom': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "PAIS"  },
'rut_rut': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "RUTA"  },
'te1_nom': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "TELEFONO 1"  },
'te2_nom': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "TELEFONO 2"  },
'te3_nom': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "TELEFONO 3"  },
'fax_nom': {type: DataTypes.CHAR(15),allowNull: false,defaultValue: ' ',comment: "FAX"  },
'ncc_nom': {type: DataTypes.CHAR(35),allowNull: false,defaultValue: ' ',comment: "NOMBRE DEL CONTACTO EN COMPRAS"  },
'ema_nom': {type: DataTypes.CHAR(250),allowNull: false,defaultValue: ' ',comment: "E-MAIL"  },
'pcc_nom': {type: DataTypes.CHAR(35),allowNull: false,defaultValue: ' ',comment: "PUESTO DEL CONTATO EN COMPRAS"  },
'tcc_nom': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "TELEFONO DEL CONTACTO EN COMPRAS"  },
'ncp_nom': {type: DataTypes.CHAR(35),allowNull: false,defaultValue: ' ',comment: "NOMBRE DEL CONTACTO EN PAGOS"  },
'pcp_nom': {type: DataTypes.CHAR(35),allowNull: false,defaultValue: ' ',comment: "PUESTO DEL CONTATO EN PAGOS"  },
'tcp_nom': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "TELEFONO CONTACTO EN PAGOS"  },
'dpa_nom': {type: DataTypes.CHAR(14),allowNull: false,defaultValue: ' ',comment: "DIAS DE PAGO SEPARADOS POR COMAS"  },
'hpa_nom': {type: DataTypes.CHAR(10),allowNull: false,defaultValue: ' ',comment: "HORAS DE PAGO"  },
'dre_nom': {type: DataTypes.CHAR(14),allowNull: false,defaultValue: ' ',comment: "DIAS DE RECEPCION DE DOCUMENTOS SEPARADOS POR COMA"  },
'hre_nom': {type: DataTypes.CHAR(10),allowNull: false,defaultValue: ' ',comment: "HORAS DE RECEPCION"  },
'ob1_nom': {type: DataTypes.CHAR(70),allowNull: false,defaultValue: ' ',comment: "OBSERVACION 1"  },
'ob2_nom': {type: DataTypes.CHAR(50),allowNull: false,defaultValue: ' ',comment: "OBSERVACION 2"  },
'ob3_nom': {type: DataTypes.CHAR(50),allowNull: false,defaultValue: ' ',comment: "OBSERVACION 3"  },
'ven_ven': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "VENDEDOR"  },
'lis_nom': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "LISTA DE PRECIOS"  },
'tip_tdn': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "TIPO DE CLIENTE O PROVEEDOR SEGUN TABLA"  },
'dcr_nom': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "DIAS DE CREDITO"  },
'lim_nom': {type: DataTypes.DECIMAL(14,2),allowNull: false,defaultValue: '0',comment: "LIMITE DE CREDIDO"  },
'mcr_nom': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "MONEDA DEL CREDITO"  },
'fea_nom': {type: DataTypes.DATE,allowNull: false,comment: "FECHA DE ALTA"  },
'emb_nom': {type: DataTypes.CHAR(40),allowNull: false,defaultValue: ' ',comment: "EMBARCAR POR"  },
'cad_cad': {type: DataTypes.CHAR(10),allowNull: false,defaultValue: ' ',comment: "CADENA COMERCIAL A LA CUAL PERTENECE"  },
'sta_nom': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "B=BAJA (STATUS REAL DEL CLIENTE O PROVEEDOR)"  },
'dst_nom': {type: DataTypes.CHAR(60),allowNull: false,defaultValue: ' ',comment: "DESCRIPCION DE ESTATUS"  },
'sa1_nom': {type: DataTypes.DECIMAL(15,2),allowNull: false,defaultValue: '0',comment: "SALDO EN LA MONEDA 1"  },
'sa2_nom': {type: DataTypes.DECIMAL(15,2),allowNull: false,defaultValue: '0',comment: "SALDO EN LA MONEDA 2"  },
'sa3_nom': {type: DataTypes.DECIMAL(15,2),allowNull: false,defaultValue: '0',comment: "SALDO EN LA MONEDA 3"  },
'sa4_nom': {type: DataTypes.DECIMAL(15,2),allowNull: false,defaultValue: '0',comment: "SALDO EN LA MONEDA 4"  },
'sa5_nom': {type: DataTypes.DECIMAL(15,2),allowNull: false,defaultValue: '0',comment: "SALDO EN LA MONEDA 5"  },
'dpp_nom': {type: DataTypes.DECIMAL(4,1),allowNull: false,defaultValue: '0',comment: "DESCUENTO POR PRONTO PAGO"  },
'ecc_nom': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "EST. CUENTAS X COBRAR B=BLOQ. D=DESB."  },
'fdo_nom': {type: DataTypes.DATE,allowNull: false,comment: "ULT. FECHA QUE SE TRATO DAR DE ALT. DOC."  },
'elc_nom': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "ESTATUS LIMITE DE CREDITO"  },
'cco_nom': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "CONSECUTIVO DE CONSIGNATARIO"  },
'pas_nom': {type: DataTypes.CHAR(130),allowNull: false,defaultValue: ' ',comment: "PASSWORD"  },
'log_nom': {type: DataTypes.CHAR(10),allowNull: false,defaultValue: ' ',comment: "LOGIN DEL CLIENTE"  },
'tte_nom': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "TIPO DE TERCERO SEGUN SAT"  },
'top_nom': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "TIPO DE OPERACION SEGUN SAT"  },
'uso_sat': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "USO DEL CFDI SEGUN TABLA DEL SAT      USO DEL CFDI ANTE EL SAT"  },
'est_nom': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "sistemas(ESTATUS A=ACTIVO M=MANTENIMIENTO D=DESACTIVO)"  },
'dvi_rut': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "DIAS DE VISITA SEPARADOS POR COMAS"  },
'oru_rut': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "ORDEN DE VISITA EN LA RUTA"  },
'mpa_nom': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "METODO DE PAGO VERSION COME2012 Y 2014"  },
'fpa_sat': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "FORMA DE PAGO SEGUN TABLA DEL SAT"  },
'tgf_nom': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "TIPO DE  GENERACION DE FACTURAS N=NO; D=DIARIO;Q=QUINCENAL;S=SEMANAL;M=MENSUAL"  },
'rtg_nom': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "RANGO SEGUN TGF_NOM PARAMETRO SEGUN PGF_NOM SI ES SEMANAL EL NUMERO 1=LUNES 7=DOMINGO"  },
'mpa_sat': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "METODO DE PAGO SEGUN TABLA DEL SAT     ver 3.3"  },
'gln_nom': {type: DataTypes.CHAR(14),allowNull: false,defaultValue: ' ',comment: "CODIGO GLN"  },
'usu_usu': {type: DataTypes.INTEGER,allowNull: true,defaultValue: '0',comment: "USUARIO"  },
'usu_cre': {type: DataTypes.INTEGER,allowNull: true,defaultValue: '0',comment: "USUARIO CREADOR" },
'tie_uac': {type: DataTypes.DATE,allowNull: true,comment: "FECHA DE LA ULTIMA ACTUALIZACION"  },
'tie_cre': {type: DataTypes.DATE,allowNull: true,comment: "FECHA DE CREACION" },
'timestamp': {type: DataTypes.INTEGER,allowNull: true,comment: "MARCA ULTIMA ACTUALIZACION"  },
'key_pri': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "LLAVE PRIMARIA PARA LA ACTUALIZACION DE VISTAS" , primaryKey: true },
createdAt: {field: 'tie_cre',type: DataTypes.DATE,},
updatedAt: {field: 'tie_uac',type: DataTypes.DATE,} 
  }, { tableName: 'man_comenom'});
};

