/* jshint indent: 2 */
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('man_comeisu', {
'tin_tti': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "TIPO DE INSUMO SEGUN TABLA COMETTI"  },
'cla_isu': {type: DataTypes.CHAR(30),allowNull: false,defaultValue: ' ',comment: "CLAVE DEL INSUMO"  },
'des_isu': {type: DataTypes.CHAR(70),allowNull: false,defaultValue: ' ',comment: "DESCRIPCION PRIMARIA"  },
'dpa_isu': {type: DataTypes.BOOLEAN,allowNull: false,defaultValue: '0',comment: "DESCRIPCION DE PASO 1:=Si .0=No"  },
'dea_isu': {type: DataTypes.STRING(2048),allowNull: false,comment: "DESCRIPCION ALTERNA"  },
'un1_isu': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "UNIDAD 1"  },
'un2_isu': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "UNIDAD 2"  },
'un3_isu': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "UNIDAD 3"  },
'fa2_isu': {type: DataTypes.DECIMAL(9,4),allowNull: false,defaultValue: '0',comment: "FACTOR DE CONVERSION 2"  },
'fa3_isu': {type: DataTypes.DECIMAL(9,4),allowNull: false,defaultValue: '0',comment: "FACTOR DE CONVERSION 3"  },
'pv1_isu': {type: DataTypes.DECIMAL(15,5),allowNull: false,defaultValue: '0',comment: "PRECIO DE VENTA 1"  },
'pv2_isu': {type: DataTypes.DECIMAL(15,5),allowNull: false,defaultValue: '0',comment: "PRECIO DE VENTA 2"  },
'pv3_isu': {type: DataTypes.DECIMAL(15,5),allowNull: false,defaultValue: '0',comment: "PRECIO DE VENTA 3"  },
'pv4_isu': {type: DataTypes.DECIMAL(15,5),allowNull: false,defaultValue: '0',comment: "PRECIO DE VENTA 4"  },
'pv5_isu': {type: DataTypes.DECIMAL(15,5),allowNull: false,defaultValue: '0',comment: "PRECIO DE VENTA 5"  },
'ta0_isu': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "TARIFA DEL IMPUESTO 0 SEGUN TABLA COMEIMP"  },
'im0_isu': {type: DataTypes.BOOLEAN,allowNull: false,defaultValue: '0',comment: "IMPUESTO 0 (1=ACTIVO 0=DESACTIVO)"  },
'ta1_isu': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "TARIFA DEL IMPUESTO 1  SEGUN TABLA COMEIMP"  },
'im1_isu': {type: DataTypes.BOOLEAN,allowNull: false,defaultValue: '0',comment: "IMPUESTO 1 (1=ACTIVO 0=DESACTIVO)"  },
'ta2_isu': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "TARIFA DEL IMPUESTO 2"  },
'im2_isu': {type: DataTypes.BOOLEAN,allowNull: false,defaultValue: '0',comment: "IMPUESTO 2 (1=ACTIVO 0=DESACTIVO)"  },
'ta3_isu': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "TARIFA DEL IMPUESTO 3"  },
'im3_isu': {type: DataTypes.BOOLEAN,allowNull: false,defaultValue: '0',comment: "IMPUESTO 3 (1=ACTIVO 0=DESACTIVO)"  },
'ta4_isu': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "TARIFA DEL IMPUESTO 4"  },
'im4_isu': {type: DataTypes.BOOLEAN,allowNull: false,defaultValue: '0',comment: "IMPUESTO 4 (1=ACTIVO 0=DESACTIVO)"  },
'ta5_isu': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "TARIFA DEL IMPUESTO 5"  },
'im5_isu': {type: DataTypes.BOOLEAN,allowNull: false,defaultValue: '0',comment: "IMPUESTO 5 (1=ACTIVO 0=DESACTIVO)"  },
'uni_sat': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "UNIDAD DE MEDIDA 1  SEGUN EL SAT"  },
'ubf_sat': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "UNIDAD BASE DE FACTURACION P=PESO; V=VOLUMEN; O=OTROS"  },
'cls_sat': {type: DataTypes.CHAR(8),allowNull: false,defaultValue: ' ',comment: "CLAVE SEGUN SAT"  },
'fum_sat': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "FACTOR DE UNIDAD DE MEDIDA EN LITRO O KILOGRAMOS SEGUN CLAVE DEL SAT"  },
'mon_isu': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "MONEDA"  },
'cst_isu': {type: DataTypes.DECIMAL(12,4),allowNull: false,defaultValue: '0',comment: "COSTO ESTANDAR"  },
'sku_isu': {type: DataTypes.CHAR(19),allowNull: false,defaultValue: ' ',comment: "SKU"  },
'est_isu': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "ESTATUS A=ACTIVO B=BLOQUEADO P=PROMOCION M=MANTENIMIENTO D=DESACTIVO"  },
'pvp_isu': {type: DataTypes.DECIMAL(15,5),allowNull: false,defaultValue: '0',comment: "PRECIO DE VENTA PROMOCION"  },
'dst_isu': {type: DataTypes.CHAR(60),allowNull: false,defaultValue: ' ',comment: "DESCRIPCION DEL ESTATUS"  },
'tci_isu': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "CLASIFICACION DE TIPO DE INVENTARIO"  },
'du1_isu': {type: DataTypes.CHAR(14),allowNull: false,defaultValue: ' ',comment: "CODIGO DUN SEGUN  UNIDDA DE MEDIDA 1"  },
'du2_isu': {type: DataTypes.CHAR(14),allowNull: false,defaultValue: ' ',comment: "CODIGO DUN SEGUN UNIDAD DE MEDIDA 2"  },
'du3_isu': {type: DataTypes.CHAR(14),allowNull: false,defaultValue: ' ',comment: "CODIGO DUN SEGUN UNIDAD DE MEDIDA 3"  },
'fra_isu': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "PERMITE FACTURACION DE FRACCIONES S=SI N=NO"  },
'usu_usu': {type: DataTypes.INTEGER,allowNull: true,defaultValue: '0',comment: "USUARIO"  },
'usu_cre': {type: DataTypes.INTEGER,allowNull: true,defaultValue: '0',comment: "USUARIO CREADOR" },
'tie_uac': {type: DataTypes.DATE,allowNull: true,comment: "FECHA DE LA ULTIMA ACTUALIZACION"  },
'tie_cre': {type: DataTypes.DATE,allowNull: true,comment: "FECHA DE CREACION" },
'timestamp': {type: DataTypes.INTEGER,allowNull: true,comment: "MARCA ULTIMA ACTUALIZACION"  },
'key_pri': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "LLAVE PRIMARIA PARA LA ACTUALIZACION DE VISTAS" , primaryKey: true },
createdAt: {field: 'tie_cre',type: DataTypes.DATE,},
updatedAt: {field: 'tie_uac',type: DataTypes.DATE,} 
  }, { tableName: 'man_comeisu'});
};

