/* jshint indent: 2 */
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('man_comecmo', {
'tdo_tdo': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "TIPO DE DOCUMENTO"  },
'ndo_doc': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "NUMERO DE DOCUMENTO"  },
'mov_mov': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "MOVIMIENTO O DETALLE DEL DOCUMENTO"  },
'pve_cfd': {type: DataTypes.DECIMAL(16,6),allowNull: false,defaultValue: '0',comment: "PRECIO DE VENTA SEGUN CFDI"  },
'can_cfd': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "CANTIDAD SEGUN CFDI"  },
'dto_cfd': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "DESCUENTO SEGUN CFDI"  },
'cla_cfd': {type: DataTypes.CHAR(30),allowNull: false,defaultValue: ' ',comment: "CLAVE DEL INUSMO DENTRO DEL DOCUMENTO"  },
'des_cfd': {type: DataTypes.STRING(1000),allowNull: false,comment: "DESCRIPCION DEL MOVIMIENTO DENTRO DEL DOCUMENTO"  },
'uni_sat': {type: DataTypes.CHAR(3),allowNull: false,defaultValue: ' ',comment: "UNIDAD MEDIDA  SEGUN SAT"  },
'ubf_sat': {type: DataTypes.CHAR(1),allowNull: false,defaultValue: ' ',comment: "UNIDAD BASE DE FACTURACION SEGUN SAT V=VOLUMEN; P=PESO; U=UNIDADES"  },
'cls_sat': {type: DataTypes.CHAR(8),allowNull: false,defaultValue: ' ',comment: "CLAVE SEGUN SAT"  },
'sku_isu': {type: DataTypes.CHAR(25),allowNull: false,defaultValue: ' ',comment: "CLAVE O SKU"  },
'uni_tca': {type: DataTypes.CHAR(25),allowNull: false,defaultValue: ' ',comment: "DESCRIPCION UNIDAD SEGUN TABLA DE CLAVES ALTERNAS"  },
'im0_mov': {type: DataTypes.DECIMAL(10,5),allowNull: false,defaultValue: '0',comment: "IMPUESTO 0  %  O CUOTA IEPS"  },
'im1_mov': {type: DataTypes.DECIMAL(10,5),allowNull: false,defaultValue: '0',comment: "IMPUESTO 1  %  O CUOTA IEPS"  },
'im2_mov': {type: DataTypes.DECIMAL(10,5),allowNull: false,defaultValue: '0',comment: "IMPUESTO 2 %  O CUOTA IEPS"  },
'im3_mov': {type: DataTypes.DECIMAL(10,5),allowNull: false,defaultValue: '0',comment: "IMPUESTO 3 %  O CUOTA IEPS"  },
'im4_mov': {type: DataTypes.DECIMAL(10,5),allowNull: false,defaultValue: '0',comment: "IMPUESTO 4 %  O CUOTA IEPS"  },
'im5_mov': {type: DataTypes.DECIMAL(10,5),allowNull: false,defaultValue: '0',comment: "IMPUESTO 5 %  O CUOTA IEPS"  },
'ba0_mov': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "BASE EN PESOS PARA CALCULO  IMPUESTO  0"  },
'ba1_mov': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "BASE EN PESOS PARA CALCULO  IMPUESTO 1"  },
'ba2_mov': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "BASE EN PESOS PARA CALCULO IMPUESTO 2"  },
'ba3_mov': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "BASE EN PESOS PARA CALCULO IMPUESTO 3"  },
'ba4_mov': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "BASE EN PESOS PARA CALCULO IMPUESTO 4"  },
'ba5_mov': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "BASE EN PESOS PARA CALCULO IMPUESTO 5"  },
'ii0_mov': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "IMPORTE DEL IMPUESTO  0"  },
'ii1_mov': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "IMPORTE DEL IMPUESTO 1"  },
'ii2_mov': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "IMPORTE DEL IMPUESTO 2"  },
'ii3_mov': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "IMPORTE DEL IMPUESTO 3"  },
'ii4_mov': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "IMPORTE DEL IMPUESTO 4"  },
'ii5_mov': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "IMPORTE DEL IMPUESTO 5"  },
'ta0_isu': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "TARIFA IMPUESTO  0 SEGUN TABLA DE IMPUESTOS"  },
'ta1_isu': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "TARIFA IMPUESTO 1 SEGUN TABLA DE IMPUESTOS"  },
'ta2_isu': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "TARIFA IMPUESTO 2 SEGUN TABLA DE IMPUESTOS"  },
'ta3_isu': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "TARIFA IMPUESTO 3 SEGUN TABLA DE IMPUESTOS"  },
'ta4_isu': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "TARIFA IMPUESTO 4 SEGUN TABLA DE IMPUESTOS"  },
'ta5_isu': {type: DataTypes.CHAR(2),allowNull: false,defaultValue: ' ',comment: "TARIFA IMPUESTO 5 SEGUN TABLA DE IMPUESTOS"  },
'pes_pro': {type: DataTypes.DECIMAL(12,4),allowNull: false,defaultValue: '0',comment: "PESO EN KILOGRAMOS"  },
'vol_pro': {type: DataTypes.DECIMAL(12,4),allowNull: false,defaultValue: '0',comment: "VOLUMEN EN LTS"  },
'oca_alm': {type: DataTypes.CHAR(4),allowNull: false,defaultValue: ' ',comment: "ORDEN EN LA  CARGA DEL CAMION"  },
'uni_cfd': {type: DataTypes.CHAR(20),allowNull: false,defaultValue: ' ',comment: "UNIDAD DEL CFDI"  },
'fum_sat': {type: DataTypes.DECIMAL(16,5),allowNull: false,defaultValue: '0',comment: "FACTOR DE UNIDAD DE MEDIDA EN LITRO O KILOGRAMOS SEGUN CLAVE DEL SAT"  },
'usu_usu': {type: DataTypes.INTEGER,allowNull: true,defaultValue: '0',comment: "USUARIO"  },
'usu_cre': {type: DataTypes.INTEGER,allowNull: true,defaultValue: '0',comment: "USUARIO CREADOR" },
'tie_uac': {type: DataTypes.DATE,allowNull: true,comment: "FECHA DE LA ULTIMA ACTUALIZACION"  },
'tie_cre': {type: DataTypes.DATE,allowNull: true,comment: "FECHA DE CREACION" },
'timestamp': {type: DataTypes.INTEGER,allowNull: true,comment: "MARCA ULTIMA ACTUALIZACION"  },
'key_pri': {type: DataTypes.INTEGER,allowNull: false,defaultValue: '0',comment: "LLAVE PRIMARIA PARA LA ACTUALIZACION DE VISTAS" , primaryKey: true },
createdAt: {field: 'tie_cre',type: DataTypes.DATE,},
updatedAt: {field: 'tie_uac',type: DataTypes.DATE,} 
  }, { tableName: 'man_comecmo'});
};

